version: '3'
services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: z_flask_api
    restart: always
    ports:
      - 7000:80
    depends_on:
      - database
    networks:
      - frontend
      - backend

  database:
    image: postgres:11.5-alpine
    container_name: z_flask_db
    restart: always
    volumes:
      - zflaskdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: zuplae
      POSTGRES_PASSWORD: zuplae
      POSTGRES_DB: zuplae
      TZ: America/Sao_Paulo
    networks:
      - backend

volumes:
  zflaskdb:
networks:
  frontend:
  backend:
